title: Default Page

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          text:
            type: blocks
            size: huge
            pretty: true
  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
      files:
        type: files

