title: Seite

columns:
  main:
    width: 2/3
    sections:
      extends: sections/body

  sidebar:
    width: 1/3
    fields:
      files:
        label: Dateien
        type: files
      date:
        label: Datum
        type: date
        display: DD. MMMM YYYY
        default: now
        time:
          display: HH.mm

options:
  changeTemplate:
    - article
    - default
