name: Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    environment: deployment

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-dev

    - name: Cache NodeJS packages
      id: nodejs-cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-nodejs-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nodejs-

    - name: Install NodeJS dependencies
      run: npm ci

    - name: Run PostCSS
      run: ./node_modules/.bin/postcss assets/css/style.css > assets/css/style.min.css

    - name: Deployment
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/content/, /site/config/config.secrets.php, /site/config/.license, /site/accounts/, /.ddev/, /media/, /.editorconfig, /.gitignore, /.git, /.github, /README.md, /node_modules/, /composer.json, /composer.lock, /package.json, /package-lock.json, /postcss.config.js, /.stylelintrc.json "
